// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdzdirylghkywylefytv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkemRpcnlsZ2hreXd5bGVmeXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDY4NzcsImV4cCI6MjA3Mzc4Mjg3N30.q-0XZSbdFXrOaTwG8AvKVynYMrSUQGV8F0OuF92BYWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});